name: Events Demo 1
on: 
  push:
    branches:
    - master
  workflow_dispatch:
  issues:
    types: [opened, edited, closed]

jobs:
  deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.actor) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."